### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by anhldbk** [albadraco/ipcamera-blu#1]
Would you please tell me how to install this plugin with my `in house` Gateblu?

**Comment by albadraco** [comment]
My request to add this module to Octoblu's Gateblu has never been acted upon by the Octoblu team.
This is a windows only node, but it doesn't require Gateblu to run. you can run it stand alone, install Node.js, then using npm install ipcamera. (npm install ipcamera-blu)  be sure you have installed the driver from: http://ip-webcam.appspot.com/  it's been a while (since I've done anything with this code), then 
1. In octoblu designer: create a generic device (get it's uuid and token)
2. cd into the installed path 
3. create the meshblu.json (this gives it's identity info, from #1 above)

```
 { 
   "uuid": "<DEVICE UUID>", 
   "token": "<DEVICE TOKEN>", 
   "server": "wss://meshblu.octoblu.com", 
   "port": "443" 
 } 
```
1. start via:  node command
2. this should turn the device in the Octoblu Designer on.

Hope this helps.

**Comment by anhldbk** [comment]
@albadraco Thank you for letting me know. 

You're right! We can run the module without using Gateblu at all.

I'm looking for a way to make `Gateblu` run on a Rasberry Pi device. The device will act as a gateway to connect to a `Meshblu` cloud.

I've read the code of `Gateblu-forever`. To my understanding, `Gateblu` does nothing special:
- Each device is installed via connectors and run in a dedicated process. There's a trouble with this approach when `Gateblu` is deployed to run on power-constrained devices.
- The connectors connect to a `Meshblu` network.
- `Gateblu` update permissions & subscribes to the devices.

Do you think that `Gateblu` suits my needs?

**Comment by albadraco** [comment]
@anhldbk via my experience gateblu on pi has been fairly stable.  I've had it running in several places, on the Raspberry Pi (v1, v2, & v3).  I guess the real question would be, how many sensors do you plan on monitoring on a single Pi and gear your implementation towards that, the more sensors, the more Pi (s) you would need, so I've had temp, motion, touch, buttons (switch), Bluetooth/Wifi (radios, reporting everything from signal strength to found MAC addresses),  all being monitored at the same time with out any issues.  I even include image recognition running (then I saw some performance issues) but the Pi2 was able to keep up under slower usage ( people arriving > 15sec apart for recognition), I suspect that would be greatly improved using the Pi3 but I haven't done any testing with that yet due to time and project redirection.

**Comment by anhldbk** [comment]
@albadraco When `gateblu`'s running (with no connectors installed), its memory footprint is around 70 MB. 
![screenshot from 2016-05-03 07-03-31](https://cloud.githubusercontent.com/assets/3270746/14971533/46db647e-10fd-11e6-8671-ee7cf65395a3.png)

The more devices to manage, the more consumed memory. Raspberry Pi 3 has 1 GB RAM. So roughly, `gateblu` can manage up to 15 devices if I use `gateblu` on Pi 3

So it's great if we can modify `gateblu` to not using a dedicated process for each device. It's reasonable, right?

**Comment by albadraco** [comment]
@anhldbk Not so sure about that I don't think the math is that cut and dry here, but in any case, monitoring 15+ devices would be pushing the limits of any rPi no matter what development platform is being used.  But, if this is something you have a keen interest in, go for it, it's a challenge.  The rPi is a great platform but does have limitations, if your project exceeds them, I'd look either at multiple rPi(s) or a bigger platform.  I am not an expert in all designs Octoblu, so please look at the people in the Octoblu team: https://www.citrix.com/blogs/product/octoblu-2/ they may be able to help you more.

**Comment by anhldbk** [comment]
@albadraco Thank you anyway!
